//
//  SignupViewController.swift
//  AuthModule
//
//  Created by Hashir Shoaib on 15/08/2022.
//  Copyright (c) 2022 hashirshoaeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ZameenSignupDisplayLogic: SignupDisplayLogic {
}

class ZameenSignupViewController: UIViewController, VIPSetup {
    // MARK: - IBOutlets
    
    @IBOutlet weak var logoImageView: UIImageView!
    @IBOutlet weak var usernameTextField: UITextField!
    @IBOutlet weak var emailTextField: UITextField!
    @IBOutlet weak var passwordTextField: UITextField!
    @IBOutlet weak var usernameErrorMessageLabel: UILabel!
    @IBOutlet weak var emailErrorMessageLabel: UILabel!
    @IBOutlet weak var passwordMessageLabel: UILabel!
    
    // MARK: - VIP Setup
    
    var interactor: ZameenSignupBusinessLogic?
    var router: (NSObjectProtocol & SignupRoutingLogic & SignupDataPassing)?
    
    internal func setup() {
        let viewController = self
        let presenter = ZameenSignupPresenter(viewController: viewController)
        let router = SignupRouter()
        let interactor = ZameenSignupInteractor(presenter: presenter) //workers could be multiple, also i think VC shouldn't know about worker
        viewController.interactor = interactor
        viewController.router = router
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: - View Life Cycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        super.prepare(for: segue, sender: sender)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    // MARK: - IBActions
    
    @IBAction func onUsernameChanged(_ sender: UITextField) {
        interactor?.onUsernameChanged(value: sender.text)
    }
    
    @IBAction func onEmailChanged(_ sender: UITextField) {
        interactor?.onEmailChanged(value: sender.text)
    }
    
    @IBAction func onPasswordChanged(_ sender: UITextField) {
        interactor?.onPasswordChanged(value: sender.text)
    }
    
    @IBAction func onSignupButtonTapped(_ sender: UIButton) {
        interactor?.onSignupButtonPressed()
    }
    
    // MARK: - Utility functions
    
}

// MARK: - Extensions

extension ZameenSignupViewController: ZameenSignupDisplayLogic {
    func showUsernameValidationError(error: String) {
        usernameErrorMessageLabel.text = error
    }
    
    func removeUsernameValidationError() {
        usernameErrorMessageLabel.text = ""
    }
    
    func showEmailValidationError(error: String) {
        emailErrorMessageLabel.text = error
    }
    
    func removeEmailValidationError() {
        emailErrorMessageLabel.text = ""
    }
    
    func showPasswordValidationError(error: String) {
        passwordMessageLabel.text = error
    }
    
    func removePasswordValidationError() {
        passwordMessageLabel.text = ""
    }
    
    func showSignupInProgress() {
        
    }
    
    func removeSignupFromProgress() {
        print("sign up success")
    }
}
