//
//  SignupPresenter.swift
//  AuthModule
//
//  Created by Hashir Shoaib on 15/08/2022.
//  Copyright (c) 2022 hashirshoaeb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SignupPresentationLogic {
    func showUsernameValidationError(error: String)
    func removeUsernameValidationError()
    func showEmailValidationError(error: String)
    func removeEmailValidationError()
    func showPasswordValidationError(error: String)
    func removePasswordValidationError()
    func showSignupInProgress()
    func removeSignupFromProgress()
    
}

class SignupPresenter: SignupPresentationLogic {
    // MARK: - VIP SETUP
    
    private let viewController: SignupDisplayLogic
    
    init(viewController: SignupDisplayLogic) {
        self.viewController = viewController
    }
    
    // MARK: - PRESENTATION LOGIC
    
    func showUsernameValidationError(error: String) {
        viewController.showUsernameValidationError(error: error)
    }
    
    func removeUsernameValidationError() {
        viewController.removeUsernameValidationError()
    }
    
    func showEmailValidationError(error: String) {
        viewController.showEmailValidationError(error: error)
    }
    
    func removeEmailValidationError() {
        viewController.removeEmailValidationError()
    }
    
    func showPasswordValidationError(error: String) {
        viewController.showPasswordValidationError(error: error)
    }
    
    func removePasswordValidationError() {
        viewController.removePasswordValidationError()
    }
    
    func showSignupInProgress() {
        viewController.showSignupInProgress()
    }
    
    func removeSignupFromProgress() {
        viewController.removeSignupFromProgress()
    }
}
