//
//  LamudiSignupInteractor.swift
//  AuthModule
//
//  Created by Hadi on 16/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LastNameBLProtocol {
    func onLastNameChanged(value: String?)
}

protocol LastNameDSProtocol {
    var lastName: String? { get set }
}

protocol LamudiSignupBusinessLogic: SignupBusinessLogic, LastNameBLProtocol {}

protocol LamudiSignupDataStore: SignupDataStore, LastNameDSProtocol {}

class LamudiSignupInteractor: SignupInteractor, LamudiSignupBusinessLogic, LamudiSignupDataStore
{
    
    var lastName: String?
//    var presenter: LamudiSignupPresentationLogic!
    
    //  var presenter: LamudiSignupPresentationLogic?
    //  var worker: LamudiSignupWorker?
    //var name: String = ""

    
    // MARK: Do something
    
    func onLastNameChanged(value: String?) {
        lastName = value
        (presenter as! LamudiSignupPresentationLogic).removeLastNameValidationError()
    }
    
    override func validate() -> Bool {
        var validationSuccess = super.validate()
        if let lastName = lastName {
            if lastName.isEmpty {
                (presenter as! LamudiSignupPresentationLogic).showLastNameValidationError(error: "Last name is empty")
                validationSuccess = false
            }
        } else {
            (presenter as! LamudiSignupPresentationLogic).showLastNameValidationError(error: "Last name is empty")
            validationSuccess = false
        }
        return validationSuccess
    }
    
//    func doSomething(request: LamudiSignup.Something.Request)
//    {
//        worker = LamudiSignupWorker()
//        worker?.doSomeWork()
//
//        let response = LamudiSignup.Something.Response()
//        presenter?.presentSomething(response: response)
//    }
}
