//
//  LamudiSignupPresenter.swift
//  AuthModule
//
//  Created by Hadi on 16/08/2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LamudiSignupPresentationLogic: SignupPresentationLogic {
    func showLastNameValidationError(error: String)
    func removeLastNameValidationError()
}

class LamudiSignupPresenter: SignupPresenter, LamudiSignupPresentationLogic {
  
  // MARK: Do something
  
    func showLastNameValidationError(error: String) {
        (viewController as! LamudiSignupDisplayLogic).showLastNameValidationError(error: error)
    }
    
    func removeLastNameValidationError() {
        (viewController as! LamudiSignupDisplayLogic).removeLastNameValidationError()
    }
}
